### ISSUE TITLE
chart.refresh is not a function?

### ISSUE THREAD

**Issue by HenryZhu-1988** [hzhqk/echarts#3]
在 echarts/dynamic echarts tree/load sub-nodes dynamicly/echarts_dynamic_tree.html
chart.refresh is not a function。

**Comment by hzhqk** [comment]
> 在 echarts/dynamic echarts tree/load sub-nodes dynamicly/echarts_dynamic_tree.html
> chart.refresh is not a function。

用Google和Edge测试并没有出现此错误，下载下来重试。echarts 远程lib也没有关闭。
